### ISSUE TITLE
"fatal error: concurrent map read and map write" from (*gcpBalancer).regeneratePicker

### ISSUE THREAD

**Issue by atetubou** [bazelbuild/remote-apis-sdks#157]
When I call ReadBlobStreamed from multiple go routines, I got the following panic.

```
fatal error: concurrent map read and map write

goroutine 23 [running]:
runtime.throw(0xcdfe2b, 0x21)
        /usr/lib/google-golang/src/runtime/panic.go:1122 +0x72 fp=0xc0000d7cf0 sp=0xc0000d7cc0 pc=0x582092
runtime.mapaccess1(0xbdf7e0, 0xc000380480, 0xc0000d7db0, 0xc00f5ecbf8)
        /usr/lib/google-golang/src/runtime/map.go:411 +0x24f fp=0xc0000d7d30 sp=0xc0000d7cf0 pc=0x55b48f
github.com/bazelbuild/remote-apis-sdks/go/pkg/balancer.(*gcpBalancer).regeneratePicker(0xc000392100)
        /usr/local/google/home/tikuta/go/src/github.com/bazelbuild/remote-apis-sdks/go/pkg/balancer/gcp_balancer.go:267 +0x147 fp=0xc0000d7e30 sp=0xc0000d7d30 pc=0xb24b07
github.com/bazelbuild/remote-apis-sdks/go/pkg/balancer.(*gcpBalancer).UpdateSubConnState(0xc000392100, 0xd93520, 0xc0207db620, 0x2, 0x0, 0x0)
        /usr/local/google/home/tikuta/go/src/github.com/bazelbuild/remote-apis-sdks/go/pkg/balancer/gcp_balancer.go:308 +0x374 fp=0xc0000d7ea8 sp=0xc0000d7e30 pc=0xb25074
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0000ee6c0)
        /usr/local/google/home/tikuta/go/src/google.golang.org/grpc/balancer_conn_wrappers.go:77 +0x357 fp=0xc0000d7fd8 sp=0xc0000d7ea8 pc=0xa66fb7
runtime.goexit()
        /usr/lib/google-golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000d7fe0 sp=0xc0000d7fd8 pc=0x5b7a01
created by google.golang.org/grpc.newCCBalancerWrapper
        /usr/local/google/home/tikuta/go/src/google.golang.org/grpc/balancer_conn_wrappers.go:60 +0x172
```

[gb.scRefs](https://github.com/bazelbuild/remote-apis-sdks/blob/6f048255943e502b14630709f22412f23a7395c3/go/pkg/balancer/gcp_balancer.go#L267) needs to be guarded by mutex?

**Comment by ola-rozenfeld** [comment]
Sorry, I've been away for a while, missed this! Has this been addressed by Kousik's latest changes?

**Comment by ola-rozenfeld** [comment]
I think Kousik fixed this. Please reopen if not.
